### ISSUE TITLE
notes with mentions in them don't seem to work

### ISSUE THREAD

**Issue by SamSamskies** [nostrband/nostr-embed#42]
here's an example: https://embed.nostr.band/?q=note1ucc8nuzemq26ympnry586lgdkfdhccehyed29es8052dxly2v5msc7k7v5

![Screenshot 2023-06-13 at 11 26 41 PM](https://github.com/nostrband/nostr-embed/assets/3655410/80c262e3-988a-4646-8e79-cf7b8f0d4cc3)

**Comment by brugeman** [comment]
Fixed v.0.1.14
