### ISSUE TITLE
deployed v0.1.18 bundle still references heynostr.com

### ISSUE THREAD

**Issue by SamSamskies** [nostrband/nostr-embed#54]
`heynostr.com` is still referenced in the bundle
https://cdn.jsdelivr.net/gh/nostrband/nostr-embed@0.1.18/dist/nostr-embed.js

v0.1.18 bundle on your release page doesn't reference it anymore though
https://github.com/nostrband/nostr-embed/releases/tag/v0.1.18

**Comment by nostrband** [comment]
Apologies, forgot how jsdelivr works. Deleted 0.1.18, added 0.1.19
